# Generated by Django 4.2.7 on 2025-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skill_profile_location_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('opacity', models.FloatField(default=0.25, help_text='0.0 - 1.0')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
